version: '3'

services:
  proxy:
    image: nginx
    ports:
      - '8080:80' 
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    deploy:
      replicas: 1
  web:
    image: httpd
    deploy:
      replicas: 3

